# Generated by Django 3.1.4 on 2020-12-17 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=14)),
                ('full_address', models.CharField(max_length=512)),
                ('name_of_university', models.CharField(max_length=256)),
                ('graduation_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(2015)])),
                ('cgpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(2)])),
                ('experience_in_months', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('current_work_place_name', models.CharField(max_length=256)),
                ('applying_in', models.CharField(choices=[('Mobile', 'Mobile'), ('Backend', 'Backend')], max_length=10)),
                ('expected_salary', models.IntegerField(validators=[django.core.validators.MaxValueValidator(60000), django.core.validators.MinValueValidator(15000)])),
                ('field_buzz_reference', models.CharField(max_length=256)),
                ('github_project_url', models.CharField(max_length=512)),
                ('on_spot_update_time', models.DateTimeField(auto_now=True)),
                ('on_spot_creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('cv_file', models.FileField(upload_to='')),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_info', to='assignment.recruitmentinformation')),
            ],
        ),
    ]
